config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#club_house'

  resources :users
  resources :posts, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]

  get    '/sign_in',  to: 'sessions#new'
  post   '/sign_in',  to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts

  has_secure_password
  before_create :remember

  attr_accessor :remember_token

  def remember
    self.remember_token = User.new_token
    self.remember_digest = User.digest(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :is_signed_in?, only: [:new, :create]

  def new
  end

  def create
    @post = current_user.posts.build(post_params)
    if (@post.save)
      redirect_to posts_path
    else
      redirect_to root_url
    end
  end

  def index
    @posts = Post.all
  end

private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def is_signed_in?
    if current_user.nil?
      flash[:danger] = "Please sign in before making posts."
      redirect_to root_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      current_user = user
      redirect_to root_url
    else
      flash.now[:danger] = "Unvalid Sign In Credentials" 
      render 'new'
    end
  end

  def destroy
    sign_out current_user if is_signed_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def club_house
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    user.remember # give the user a new token(avoid becoming 'stale')
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def sign_out(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user
    if (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user 
        sign_in user
        current_user = user
      end
    else
      nil
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def is_signed_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<p> <b> <%= post.title %></b></p><br>
<p> <%= post.content  %> </p><br>
<% if is_signed_in? %>
<p> Post by: <%= User.find_by(id: post.user_id).name %></p>
<% end %>
<p> ----------------------------------------  </p>   

app/views/posts/index.html.erb
<h1>All Posts</h1>

<ul>
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<h1> Create a New Post </h1>

<%= form_for :post, url: posts_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit "Create Post!" %>
<% end %>

app/views/static_pages/club_house.html.erb
<h1> Welcome to the Club House!</h1>

<% if is_signed_in? %>
  <p> You are currently signed as <%= current_user.name %>.</p>
  <%= link_to "Create a Post", new_post_path(current_user) %><br>
<% else %>
  <p> You are currently not signed in.</p>
<% end %>

<%= link_to("Sign in to see who authors' of posts", sign_in_path ) %>
<br>
<%= link_to "Sign Out", sign_out_path, method: :delete %> <br>

<%= link_to "See Posts", posts_path %>